# Generated by Django 5.1.4 on 2025-05-19 09:06

from django.db import migrations


def create_initial_game_data(apps, schema_editor):
    # Get model references
    Deck = apps.get_model('game', 'Deck')
    Card = apps.get_model('game', 'Card')
    
    # Create reference deck
    reference_deck = Deck.objects.create(
        name="Alice is Missing Reference Deck",
        deck_type="reference"
    )
    
    # Create character cards
    character_cards = [
        {
            "title": "Charlie Barnes",
            "description": "Charlie is Alice's ex and still harbors feelings for her. Known for having a temper, but is genuinely concerned about her disappearance.",
            "card_type": "character",
        },
        {
            "title": "Dakota Travis",
            "description": "Dakota is Alice's best friend who knows all her secrets. Was the last person to see Alice before she disappeared.",
            "card_type": "character",
        },
        {
            "title": "Evan Holwell",
            "description": "Evan is Alice's cousin who recently moved to Silent Falls. Has been trying to find his place in town and was close to Alice.",
            "card_type": "character",
        },
        {
            "title": "Jack Briarwood",
            "description": "Jack is Alice's older brother who left Silent Falls for college but returned when he heard about his sister's disappearance.",
            "card_type": "character",
        },
        {
            "title": "Julia Reeves",
            "description": "Julia is Alice's childhood friend who grew apart from her in recent years. Feels guilty about their falling out.",
            "card_type": "character",
        },
    ]
    
    for card_data in character_cards:
        Card.objects.create(
            title=card_data["title"],
            description=card_data["description"],
            card_type=card_data["card_type"],
            deck=reference_deck,
        )
    
    # Create location cards
    location_cards = [
        {
            "title": "Silent Falls High School",
            "description": "The local high school where Alice attended. Recently there have been rumors of strange activities happening after hours.",
            "card_type": "location",
        },
        {
            "title": "Twin Lakes",
            "description": "A secluded spot outside of town where teenagers often go to hang out. Alice mentioned she was meeting someone there the night she disappeared.",
            "card_type": "location",
        },
        {
            "title": "The Old Mill",
            "description": "An abandoned mill at the edge of town with a dark history. Local legend says it's haunted by the ghosts of workers who died there.",
            "card_type": "location",
        },
        {
            "title": "Briarwood Family Home",
            "description": "Alice's home where she lived with her parents. Her room remains untouched since her disappearance.",
            "card_type": "location",
        },
        {
            "title": "Main Street Diner",
            "description": "A popular hangout spot for the local teenagers. Alice worked part-time as a waitress here.",
            "card_type": "location",
        },
    ]
    
    for card_data in location_cards:
        Card.objects.create(
            title=card_data["title"],
            description=card_data["description"],
            card_type=card_data["card_type"],
            deck=reference_deck,
        )
    
    # Create motive cards
    motive_cards = [
        {
            "title": "Running Away",
            "description": "Evidence suggests Alice may have been planning to leave Silent Falls for some time. Her diary mentions feeling trapped and needing to escape.",
            "card_type": "motive",
        },
        {
            "title": "Forbidden Relationship",
            "description": "Alice may have been involved with someone her parents disapproved of, leading to conflict that pushed her to leave or hide.",
            "card_type": "motive",
        },
        {
            "title": "Witness to a Crime",
            "description": "Alice might have seen something she wasn't supposed to see, putting her in danger from those involved.",
            "card_type": "motive",
        },
        {
            "title": "Family Secrets",
            "description": "The Briarwood family has some dark secrets that Alice may have discovered, leading to her disappearance.",
            "card_type": "motive",
        },
        {
            "title": "Supernatural Encounter",
            "description": "Silent Falls has a history of strange occurrences. Alice had been researching local legends shortly before she disappeared.",
            "card_type": "motive",
        },
    ]
    
    for card_data in motive_cards:
        Card.objects.create(
            title=card_data["title"],
            description=card_data["description"],
            card_type=card_data["card_type"],
            deck=reference_deck,
        )
    
    # Create clue cards with reveal times
    clue_cards = [
        {
            "title": "Alice's Diary",
            "description": "A hidden diary found under Alice's bed reveals her feelings of being watched and plans to meet someone secretly.",
            "card_type": "clue",
            "reveal_time": 10,
        },
        {
            "title": "Strange Text Messages",
            "description": "Alice's phone records show cryptic messages from an unknown number in the weeks before her disappearance.",
            "card_type": "clue",
            "reveal_time": 20,
        },
        {
            "title": "Abandoned Car",
            "description": "Alice's car was found abandoned at Twin Lakes with the driver's door open and her keys still in the ignition.",
            "card_type": "clue",
            "reveal_time": 30,
        },
        {
            "title": "Security Camera Footage",
            "description": "Footage from the gas station shows Alice buying supplies late at night, acting nervous and constantly looking over her shoulder.",
            "card_type": "clue",
            "reveal_time": 45,
        },
        {
            "title": "Mysterious Necklace",
            "description": "A necklace not belonging to Alice was found in her room, bearing a symbol connected to a local cult.",
            "card_type": "clue",
            "reveal_time": 60,
        },
        {
            "title": "Final Phone Call",
            "description": "Alice's last phone call was to an unknown number. The recording contains the sound of rain, footsteps, and a muffled conversation.",
            "card_type": "clue",
            "reveal_time": 75,
        },
    ]
    
    for card_data in clue_cards:
        Card.objects.create(
            title=card_data["title"],
            description=card_data["description"],
            card_type=card_data["card_type"],
            deck=reference_deck,
            reveal_time=card_data["reveal_time"],
        )
    
    # Create suspect cards
    suspect_cards = [
        {
            "title": "Mr. Collins",
            "description": "Alice's history teacher who had an unusual interest in her academic progress. Recently had a heated argument with Alice that was overheard by other students.",
            "card_type": "suspect",
        },
        {
            "title": "The Stranger",
            "description": "A mysterious person who arrived in Silent Falls a few weeks before Alice's disappearance. No one knows much about them, but Alice was seen talking to them on several occasions.",
            "card_type": "suspect",
        },
        {
            "title": "Robert Briarwood",
            "description": "Alice's father who has been acting strangely since her disappearance. Financial records show large withdrawals from his bank account recently.",
            "card_type": "suspect",
        },
        {
            "title": "The Silent Falls Cult",
            "description": "A secretive group operating on the outskirts of town. Rumors suggest they've been recruiting young people for unknown purposes.",
            "card_type": "suspect",
        },
        {
            "title": "Former Friend Group",
            "description": "Alice recently had a falling out with her old friends. Some have been spreading rumors about her and may have had motives to harm her.",
            "card_type": "suspect",
        },
    ]
    
    for card_data in suspect_cards:
        Card.objects.create(
            title=card_data["title"],
            description=card_data["description"],
            card_type=card_data["card_type"],
            deck=reference_deck,
        )
    
    print("Initial game data created successfully!")


def remove_initial_game_data(apps, schema_editor):
    # Get model references
    Deck = apps.get_model('game', 'Deck')
    
    # Delete reference deck (this will cascade delete all cards)
    Deck.objects.filter(name="Alice is Missing Reference Deck").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_game_data, remove_initial_game_data),
    ]
