# Generated by Django 5.2.1 on 2025-05-19 19:19

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_message_image_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_type',
            field=models.CharField(blank=True, choices=[('alert', 'Alert'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.get_message_image_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='game.player'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='game.player'),
        ),
    ]
